### ISSUE TITLE
md0 error

### ISSUE THREAD

**Issue by tiagogbarbosa** [uxora-com/xpenology-docker#19]
Hello,

Im having this problem with redpill and this docker image
When i click on install.. this appear
![image](https://user-images.githubusercontent.com/8936001/210278336-6535183f-a6d5-4e7a-9cf0-ed380337cd2f.png)

After reboot
![image](https://user-images.githubusercontent.com/8936001/210278406-417bc5e8-8532-4596-a3c4-9a016fe8d2c9.png)
![image](https://user-images.githubusercontent.com/8936001/210278418-a8bcc159-99ec-4d8c-b480-974d7f6bd68f.png)
Again..

Any tips?
Ty

**Comment by uxora-com** [comment]
Should be fixed with update and rr bootloader.
